### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by Aetherinox** [jaedle/mirror-to-gitea#15]
Hey,

I have my docker-compose.yml which has my Gitea / Github credentials. However, when I review the docker logs for mirror-to-gitea, I keep getting an error about bad credentials, and then also a syntax error

```
/app/node_modules/@octokit/request/dist-node/index.js:86
      const error = new requestError.RequestError(toErrorMessage(data), status, {
```

```json
Node.js v18.14.2
Starting to create mirrors...
/app/node_modules/@octokit/request/dist-node/index.js:86
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
    at /app/node_modules/@octokit/request/dist-node/index.js:86:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.next (/app/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:112:28)
    at async getGithubRepositories (/app/src/index.js:11:39)
    at async main (/app/src/index.js:121:30) {
  status: 401,
  response: {
    url: 'https://api.github.com/users/aetherinox/repos',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 13 Nov 2023 22:18:12 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'C65A:7056:C11DB9:18F414A:6552A0A3',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '30',
      'x-ratelimit-reset': '1699916753',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '30',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/users/aetherinox/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/18.14.2 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}

Node.js v18.14.2
```

I've checked those credentials over and over, and they appear correct. I'm even using them for another service. So I'm not sure what I'm missing here.

It was running fine before, and I noticed I created a new repo on Github but it never moved over to Gitea. So I checked docker and the process kept getting restarted every 5 or so seconds, and that's what popped up in the logs.

I even created a fresh Personal Access Token just for mirror-to-gitea, and same error.

**Comment by jaedle** [comment]
Hey :wave: 

I'm sorry that something seems to be broken. :cry: 

As 401/403 errors may be pretty hard to debug, redoing the same request as `mirror-to-gitea` with curl may help. Would you mind performing the following command?

```sh
curl -fsS https://api.github.com/users/aetherinox/repos -o /dev/null -D - -H "Authorization: Bearer $GITHUB_TOKEN"
```

Please make sure to have the environment variable `GITHUB_TOKEN` set with the same token you are using with mirror-to-gitea.

**Comment by Aetherinox** [comment]
Here is the output
```
HTTP/2 200 
server: GitHub.com
date: Wed, 15 Nov 2023 23:05:52 GMT
content-type: application/json; charset=utf-8
content-length: 159055
cache-control: private, max-age=60, s-maxage=60
vary: Accept, Authorization, Cookie, X-GitHub-OTP
etag: "9fab3c47662da9a530ff6572e8eba3452c1b4aaafgf2451e0e10590ff17f0144"
github-authentication-token-expiration: 2024-11-09 00:00:00 -0700
x-github-media-type: github.v3; format=json
x-accepted-github-permissions: metadata=read
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4984
x-ratelimit-reset: 1700090400
x-ratelimit-used: 16
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: D15C:15AB:4B1670:11372F8:46663ACF
```

Seems to be returning the same thing. And this was done on the same machine that is running mirror-to-gitea.

**Comment by jaedle** [comment]
Closed due to staleness
